Feature/cronjob trigger process
konstellation-io/kai-processes pull request #13
Opened 2023-10-09 14:45 UTC by kafkaphoenix

## Description

New process cronjob trigger that given a cron expression and a message will send that message through sdk messaging with a time bases depending on the cron

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-10-10 10:30 UTC, alexrodfe commented on cronjob-trigger/README.md
> +### Input
Instead of input I believe this should be "config" then tell the "keys" the .yaml is waiting for

2023-10-10 10:38 UTC, alexrodfe approved these changes

2023-10-11 07:56 UTC, dfinteligenz requested changes

2023-10-11 07:56 UTC, dfinteligenz commented on cronjob-trigger/README.md
> +```
```suggestion
### Config 

The configuration should be defined inside the `centralized configuration scope`, for example:

| Key            | Optional  | Type | Value                                                                                         |
|----------------|-----------|------|-----------------------------------------------------------------------------------------------|
| cron | no        | str  | Cron expression     |
| message | yes        | str  | Message to be sent in the generated events      |
```

2023-10-11 07:56 UTC, dfinteligenz commented on cronjob-trigger/README.md
> +
Add the response event structure as a table with the format:

```
| Key       | Type | Value                                                                  |
|-----------|------|------------------------------------------------------------------------|
| requestID | str  | A string uuid                                                          |
| message  | str  | The defined message (if any(                             |
| time     | str  | The timestamp of the generated event                                |
```

2023-10-11 07:56 UTC, dfinteligenz commented on cronjob-trigger/README.md
> +
Also, add a real JSON example of the event below.

2023-10-11 07:56 UTC, dfinteligenz commented on cronjob-trigger/app.yaml
> +    bucket: product
```suggestion
centralized_configuration:
  global:
    bucket: global
  product:
    bucket: product
```

2023-10-11 07:56 UTC, dfinteligenz commented on github-webhook-trigger/README.md
This has been already changed in the PR https://github.com/konstellation-io/kai-processes/pull/14, please revert this changes @kafkaphoenix

2023-10-11 09:22 UTC, alexrodfe approved these changes

2023-10-11 10:25 UTC, dfinteligenz commented on github-webhook-trigger/README.md
> +### Input
```suggestion
## Input 
```

2023-10-11 10:26 UTC, dfinteligenz commented on cronjob-trigger/README.md
> +### Config
```suggestion
## Input 
```

2023-10-11 10:26 UTC, dfinteligenz commented on cronjob-trigger/README.md
> +#### Example
```suggestion
### Example
```

2023-10-11 10:29 UTC, dfinteligenz requested changes
Check the comments above

2023-10-11 10:58 UTC, dfinteligenz approved these changes

2023-10-11 10:58 UTC, merged

2024-02-12 17:21 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/cronjob-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:24 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 0.2.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/github-webhook-trigger/v0.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:28 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/gitlab-webhook-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:32 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/grpc-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:36 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/kafka-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:40 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/process-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:44 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/rest-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: