Feature: New gitlab webhook
konstellation-io/kai-processes pull request #14
Opened 2023-10-09 16:48 UTC by alexrodfe

## Description

- Added new predefined process gitlab webhook
- Updated docs

## Motivation and Context

Users will now be able to use a Gitlab webhook if they want to trigger any workflow from a Gitlab repo event.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [X] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-10-10 07:18 UTC, kafkaphoenix approved these changes
good job!

2023-10-11 07:46 UTC, dfinteligenz requested changes

2023-10-11 07:46 UTC, dfinteligenz commented on github-webhook-trigger/README.md
> +| event     | str  | The name of the event that has occurred                                |
I'd add a real example of the output below the table,  in JSON format.

2023-10-11 07:46 UTC, dfinteligenz commented on gitlab-webhook-trigger/README.md
> +| event     | str  | The name of the event that has occurred                                |
I'd add a real example of the output below the table, in JSON format.

2023-10-11 07:46 UTC, dfinteligenz commented on gitlab-webhook-trigger/app.yaml
> +    bucket: product
```suggestion
centralized_configuration:
  global:
    bucket: global
  product:
    bucket: product
```

2023-10-11 07:46 UTC, dfinteligenz commented on gitlab-webhook-trigger/minikube_build.sh
> +minikube image build -t kai-processes/github-webhook-trigger . -f develop.Dockerfile -p kai-local
```suggestion
minikube image build -t kai-processes/gitlab-webhook-trigger . -f develop.Dockerfile -p kai-local
```

2023-10-11 07:46 UTC, dfinteligenz commented on gitlab-webhook-trigger/sonar-project.properties
> +sonar.projectName=Kai Processes - Github Webhook Trigger
```suggestion
sonar.projectName=Kai Processes - GitLab Webhook Trigger
```

2023-10-11 07:46 UTC, dfinteligenz commented on gitlab-webhook-trigger/sonar-project.properties
> +sonar.projectKey=konstellation-io_kai-processes_github_webhook_trigger
```suggestion
sonar.projectKey=konstellation-io_kai-processes_gitlab_webhook_trigger
```

2023-10-11 07:49 UTC, dfinteligenz commented on github-webhook-trigger/README.md
> +| github_secret  | yes       | str  | Github's webhook secret
```suggestion
| Key            | Optional  | Type | Value                                                                                         |
|----------------|-----------|------|-----------------------------------------------------------------------------------------------|
| webhook_events | no        | str  | Possible options (comma separated): push, pull, release, workflow_dispatch, workflow_run      |
| github_secret  | yes       | str  | Github's webhook secret.  |
```

2023-10-11 11:21 UTC, dfinteligenz approved these changes

2023-10-11 15:33 UTC, merged

2024-02-12 17:21 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/cronjob-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:24 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 0.2.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/github-webhook-trigger/v0.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:32 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/grpc-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:36 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/kafka-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:40 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/process-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:44 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/rest-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: