Feature: kafka trigger
konstellation-io/kai-processes pull request #24
Opened 2023-10-31 20:04 UTC by alexrodfe

## Description

- Added the new kafka trigger
- Added documentation on usage

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-11-02 08:25 UTC, dfinteligenz requested changes

2023-11-02 08:25 UTC, dfinteligenz commented on kafka-trigger/README.md
> +| insecure_skip_verify | yes        | bool  | Skip SSL certificate validation  |
```suggestion
| insecure_skip_verify | yes        | bool  | Skip SSL certificate validation, defaults to false  |
```

2023-11-02 08:25 UTC, dfinteligenz commented on kafka-trigger/README.md
> +| message   | []byte  | The message's payload    |
```suggestion
| payload   | []byte  | The event's payload    |
```

2023-11-02 08:25 UTC, dfinteligenz commented on kafka-trigger/sonar-project.properties
You need to modify the CI to execute the tests and upload the results to Sonar.

If you need me to create a new project for this trigger, please just ask me.

2023-11-02 09:34 UTC, dfinteligenz commented on kafka-trigger/README.md
> +| insecure_skip_verify | yes        | bool  | Skip SSL certificate validation  |
Id' also rename the `insecure_skip_verify` to `skip_tls_verify`, IMO it's easier to understand.

2023-11-03 14:28 UTC, dfinteligenz commented on kafka-trigger/kafkacluster.go
Do we still need this file @alexrodfe , given that we are using the testcontainer predefined image

2023-11-03 14:41 UTC, dfinteligenz requested changes
Check comments above

2023-11-03 14:54 UTC, alexrodfe commented on kafka-trigger/kafkacluster.go
No we don't. I'll delete it

2023-11-06 11:31 UTC, JYisus commented on kafka-trigger/main.go
> +			Timeout:   10 * time.Second,
Maybe this could be defined in config or as a constant

2023-11-06 11:33 UTC, JYisus commented on kafka-trigger/main.go
> +		err := r.Close() // reader must be gracefully closed
To ensure this is always called, call it with a defer in the first line of the goroutine

2023-11-06 11:36 UTC, JYisus commented on kafka-trigger/main.go
> +	err = r.Close() // reader must be gracefully closed
This is already been called in the goroutine, isn't it?

2023-11-06 11:37 UTC, JYisus commented on kafka-trigger/main.go
> +	termChan := make(chan os.Signal, 1)
IMO, this logic to handle external signals to exit the program should be in the main function

2023-11-06 11:38 UTC, JYisus requested changes
Great job! Just a few things.

2023-11-07 12:46 UTC, alexrodfe commented on kafka-trigger/main.go
> +	termChan := make(chan os.Signal, 1)
Main function launches runner, runner wakes up two go functions (runner and subscriber) then waits for them, subscriber stands waiting for sigterm. Runner should also be waiting for sigterm, if it wasnt, runner would end execution, then closing the go rutine inside

2023-11-07 12:46 UTC, alexrodfe commented on kafka-trigger/main.go
> +	err = r.Close() // reader must be gracefully closed
Yes but it was here to complete all posible scenarios, I'll add a defer as referred previously, so this line will no longer be needed

2023-11-07 12:47 UTC, alexrodfe commented on kafka-trigger/main.go
> +		err := r.Close() // reader must be gracefully closed
I wasn't adding a defer so I could check on the error but I agree, defer is much cleaner

2023-11-07 12:48 UTC, alexrodfe commented on kafka-trigger/main.go
> +			Timeout:   10 * time.Second,
I'll have it as a constant

2023-11-07 15:11 UTC, dfinteligenz approved these changes

2023-11-08 08:32 UTC, JYisus approved these changes

2023-11-08 09:21 UTC, merged

2024-02-12 17:20 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/cronjob-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:23 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 0.2.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/github-webhook-trigger/v0.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:27 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/gitlab-webhook-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:31 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/grpc-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:35 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/kafka-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:39 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/process-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:43 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/rest-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: