Feat/knt1 381 GitHub webhook trigger
konstellation-io/kai-processes pull request #4
Opened 2023-07-19 12:28 UTC by kafkaphoenix

## Description

Github webhook trigger

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ x] I have created tests for my code changes, and the tests are passing.
- [x ] I have executed the pre-commit hooks locally.
- [ x] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ x] I have updated the documentation accordingly.

Developers:
@alexrodfe 
@kafkaphoenix

2023-07-21 07:15 UTC, dfinteligenz requested changes
Good job!
Just check out some comments below.

2023-07-21 07:15 UTC, dfinteligenz commented on github-webhook-trigger/internal/webhook/webhook.go
> +	path = "/webhooks"
As we will be listening to a single webhook, I'd change the path to singular.

```suggestion
	path = "/webhook"
```

2023-07-21 07:15 UTC, dfinteligenz commented on github-webhook-trigger/internal/webhook/webhook.go
> +	eventConfig, githubSecret, err := getConfig(kaiSDK)
The GitHub secret should be optional, what happens if the secret is not given?

2023-07-21 07:15 UTC, dfinteligenz commented on github-webhook-trigger/internal/webhook/webhook_test.go
> +	allTests = append(allTests, IgnoredTests...)
I'd add the `IgnoredTests` slice element. to the existing `okTests` slice, and rename it to `testsUseCases`

2023-07-21 07:15 UTC, dfinteligenz commented on github-webhook-trigger/internal/webhook/webhook_test.go
> +	}
You can replace this loop for `s.ContainsSameElements()`

2023-07-21 10:17 UTC, alexrodfe commented on .gitignore
> +*.code-workspace
I agree

2023-07-21 10:18 UTC, alexrodfe commented on README.md
> +The github webhook trigger is a predefined KIO process that creates a webhook listener to a github repository. It will stay listening to user requested events, then trigger a KAI workflow on said eve
First I thought about writing KAI, but isn't KAI the platform and KIO the whole global concept?
I mean, KAI describes the platform used to upload versions but I don't know if versions, products, belong to KAI instead of KIO as the whole Konstellation ecosystem

2023-07-21 11:10 UTC, alexrodfe commented on github-webhook-trigger/internal/webhook/webhook_test.go
> +	}
testify suites don't have said method

2023-07-24 05:38 UTC, dfinteligenz commented on README.md
> +The github webhook trigger is a predefined KIO process that creates a webhook listener to a github repository. It will stay listening to user requested events, then trigger a KAI workflow on said eve
KAI refers to Konstellation AI, which refers to the whole ecosystem.
We have named the server KAI too because the KAI-Server was redundant, but it refers to the server side.

2023-07-24 05:46 UTC, dfinteligenz commented on github-webhook-trigger/internal/webhook/webhook_test.go
> +	}
My bad, I meant `s.ElementsMatch`

2023-07-24 05:47 UTC, dfinteligenz requested changes
Check the comments below, please!

2023-07-24 07:06 UTC, kafkaphoenix commented on github-webhook-trigger/internal/webhook/webhook_test.go
> +	}
really useful method thanks!

2023-07-24 07:07 UTC, kafkaphoenix commented on README.md
> +The github webhook trigger is a predefined KIO process that creates a webhook listener to a github repository. It will stay listening to user requested events, then trigger a KAI workflow on said eve
updated

2023-07-24 08:10 UTC, dfinteligenz approved these changes
Great job team!

2023-07-24 08:10 UTC, merged

2024-02-12 17:21 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/cronjob-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:25 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 0.2.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/github-webhook-trigger/v0.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:28 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/gitlab-webhook-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:36 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/kafka-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:40 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/process-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-12 17:44 UTC, IGZEnriqueRomera commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/kai-processes/releases/tag/rest-trigger/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: